#####################################################
#
# CREADO POR PEDRO REINA ROJAS (apachebcn@gmail.com)
#
#####################################################


version: "3"

services:

    prod_pgadmin:
        container_name: "${CONTAINER_NAME}_pgadmin"
        image: dpage/pgadmin4
        depends_on:
            - db
        restart: always
        ports:
            - 0.0.0.0:${PGADMIN_PORT}:83
        volumes:
            - ./volumes/pgadmin:/root/.pgadmin
        environment:
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - PGADMIN_DEFAULT_EMAIL=admin@admin.es
            - PGADMIN_DEFAULT_PASSWORD=admin
        networks:
            - docker-network
        labels:
            traefik.enable: "false"